import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Papa from 'papaparse';
import * as XLSX from 'xlsx';
import { mean, median, standardDeviation, sampleCorrelation, linearRegression, linearRegressionLine } from 'simple-statistics';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ScatterChart, Scatter, LineChart, Line, Cell } from 'recharts';
import { Brain, CheckCircle2, AlertTriangle, CircleAlert, Mic2, VolumeX, Sparkles, Download, Play, ChevronLeft, ChevronRight, HelpCircle, FlaskConical, FileText, BarChart3 } from 'lucide-react';
import './styles.css';

const steps = [
  'Data Upload & Smart Cleaning','Data Overview','Research Design Wizard','Variables & Measurement Scales','Statistical Test Recommendation','Assumptions & Diagnostics','In-App Statistical Analysis','Interpretation & APA Reporting','Visualizations','Learning & Tutor Mode','Summary & Export'
];

const sampleRows = [
  {id:1, leadership:4.2, culture:4.0, engagement:4.5, performance:88, group:'Intervention', gender:'Female'},
  {id:2, leadership:3.1, culture:3.5, engagement:3.4, performance:74, group:'Control', gender:'M'},
  {id:3, leadership:4.8, culture:4.7, engagement:4.9, performance:94, group:'Intervention', gender:'female'},
  {id:4, leadership:2.4, culture:2.9, engagement:2.8, performance:66, group:'Control', gender:'Male'},
  {id:5, leadership:3.9, culture:4.1, engagement:4.0, performance:85, group:'Intervention', gender:'F'},
  {id:6, leadership:2.8, culture:3.0, engagement:3.1, performance:71, group:'Control', gender:'male'},
  {id:7, leadership:4.5, culture:4.4, engagement:4.6, performance:91, group:'Intervention', gender:'Female'},
  {id:7, leadership:4.5, culture:4.4, engagement:4.6, performance:91, group:'Intervention', gender:'Female'},
  {id:8, leadership:'99', culture:3.2, engagement:3.2, performance:72, group:'Control', gender:'M'}
];

function inferType(values){ const clean=values.filter(v=>v!==''&&v!=null); const nums=clean.filter(v=>!Number.isNaN(Number(v))); if(nums.length/Math.max(clean.length,1)>.85){ const uniq=[...new Set(nums.map(Number))]; if(uniq.length<=7 && uniq.every(n=>Number.isInteger(n)|| (n>=1&&n<=5))) return 'Likert-type'; return 'numeric'; } if(clean.some(v=>!Number.isNaN(Date.parse(v))) && clean.length>0) return 'date'; return 'categorical'; }
function cols(rows){ return rows[0]?Object.keys(rows[0]):[]; }
function health(rows){ const columns=cols(rows); const duplicateCount=rows.length-new Set(rows.map(r=>JSON.stringify(r))).size; const missing=columns.reduce((a,c)=>({...a,[c]:rows.filter(r=>r[c]===''||r[c]==null).length}),{}); const typeInfo=columns.map(c=>({name:c,type:inferType(rows.map(r=>r[c]))})); const outliers=[]; typeInfo.filter(t=>['numeric','Likert-type'].includes(t.type)).forEach(t=>{const vals=rows.map(r=>Number(r[t.name])).filter(Number.isFinite); if(vals.length>2){ const m=mean(vals), sd=standardDeviation(vals)||0; rows.forEach((r,i)=>{const z=sd?Math.abs((Number(r[t.name])-m)/sd):0; if(z>3 || (t.type==='Likert-type' && (Number(r[t.name])<1 || Number(r[t.name])>5))) outliers.push({row:i+1,column:t.name,value:r[t.name]});}); }}); const inconsistent=typeInfo.filter(t=>t.type==='categorical').flatMap(t=>{const lowered=[...new Set(rows.map(r=>String(r[t.name]??'').trim().toLowerCase()).filter(Boolean))]; const raw=[...new Set(rows.map(r=>String(r[t.name]??'').trim()).filter(Boolean))]; return raw.length>lowered.length? [{column:t.name,raw:raw.join(', ')}]:[];}); return {duplicateCount,missing,typeInfo,outliers,inconsistent}; }
function cleanData(rows){ const seen=new Set(); return rows.filter(r=>{const key=JSON.stringify(r); if(seen.has(key)) return false; seen.add(key); return true;}).map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>{ let nv=v; if(typeof nv==='string' && nv.trim()!=='' && !Number.isNaN(Number(nv))) nv=Number(nv); if(k.toLowerCase().includes('gender')) { const s=String(nv).toLowerCase(); if(['m','male'].includes(s)) nv='Male'; if(['f','female'].includes(s)) nv='Female'; } if(['leadership','culture','engagement'].includes(k) && Number(nv)>5) nv=null; return [k,nv]; }))); }
function descriptives(rows){ return cols(rows).map(c=>{const vals=rows.map(r=>r[c]).filter(v=>v!==''&&v!=null); const type=inferType(vals); if(['numeric','Likert-type'].includes(type)){ const nums=vals.map(Number).filter(Number.isFinite); return {name:c,type,N:nums.length,mean:fmt(mean(nums)),median:fmt(median(nums)),sd:fmt(nums.length>1?standardDeviation(nums):0),min:Math.min(...nums),max:Math.max(...nums)}; } const counts={}; vals.forEach(v=>counts[v]=(counts[v]||0)+1); return {name:c,type,N:vals.length,counts}; }); }
function fmt(n){ return Number.isFinite(n)?Number(n).toFixed(2):'—'; }
function corr(rows,x,y){ const pairs=rows.map(r=>[Number(r[x]),Number(r[y])]).filter(p=>p.every(Number.isFinite)); return pairs.length>2?sampleCorrelation(pairs.map(p=>p[0]),pairs.map(p=>p[1])):NaN; }
function App(){ const [mode,setMode]=useState(null), [step,setStep]=useState(0), [muted,setMuted]=useState(false), [rows,setRows]=useState(sampleRows), [cleaned,setCleaned]=useState(cleanData(sampleRows)), [useClean,setUseClean]=useState(true), [attempts,setAttempts]=useState({}), [roles,setRoles]=useState({performance:'Dependent variable',leadership:'Independent variable',culture:'Control',engagement:'Mediator'}), [analysis,setAnalysis]=useState(null); const data=useClean?cleaned:rows; const h=useMemo(()=>health(rows),[rows]); const desc=useMemo(()=>descriptives(data),[data]); const variables=cols(data); const numeric=desc.filter(d=>['numeric','Likert-type'].includes(d.type)).map(d=>d.name);
 const guide=`Step ${step} of 10: ${steps[step]}. StatMentor keeps computation inside the app and guides each choice in plain language.`;
 const speak=()=>{ if(!muted && 'speechSynthesis' in window){ speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(guide)); }};
 async function upload(e){ const f=e.target.files?.[0]; if(!f) return; if(f.name.endsWith('.csv')) Papa.parse(f,{header:true,dynamicTyping:true,complete:r=>{setRows(r.data.filter(x=>Object.keys(x).length)); setCleaned(cleanData(r.data));}}); else { const buf=await f.arrayBuffer(); const wb=XLSX.read(buf); const ws=wb.Sheets[wb.SheetNames[0]]; const json=XLSX.utils.sheet_to_json(ws); setRows(json); setCleaned(cleanData(json)); }}
 function runAnalysis(){ const x=roles.iv||numeric.find(n=>n!=='performance')||numeric[0], y=roles.dv||'performance'; const r=corr(data,x,y); const pairs=data.map(row=>({x:Number(row[x]),y:Number(row[y])})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)); const lr=linearRegression(pairs.map(p=>[p.x,p.y])); setAnalysis({test:'Pearson correlation + simple linear regression',x,y,n:pairs.length,r, r2:r*r, slope:lr.m, intercept:lr.b, apa:`A Pearson correlation showed a ${Math.abs(r)>.5?'strong':'moderate'} positive association between ${x} and ${y}, r(${pairs.length-2}) = ${fmt(r)}, p < .05. A simple linear regression indicated that ${x} explained ${fmt(r*r*100)}% of variance in ${y}.`}); }
 if(!mode) return <Shell muted={muted} setMuted={setMuted}><section className="hero"><div><p className="eyebrow">AI-guided doctoral statistics</p><h1>StatMentor AI</h1><p>A friendly statistics advisor that cleans data, checks assumptions, recommends tests, runs analyses internally, and writes APA-style results without sending users to SPSS, SAS, R, or other analysis tools.</p><button onClick={()=>setMode('guided')}>Start Guided Tour (recommended)</button><button className="ghost" onClick={()=>setMode('pilot')}>I know what I need – Let me choose (Pilot Mode)</button></div><Brain size={160}/></section></Shell>;
 return <Shell muted={muted} setMuted={setMuted}><aside className="rail">{steps.map((s,i)=><button key={s} onClick={()=>mode==='pilot'||i<=step?setStep(i):null} className={i===step?'active':''}>{i}. {s}</button>)}</aside><main className="card"><div className="guide"><Sparkles/><p>{guide}</p><button onClick={speak}><Mic2/> Play Guide Voice</button></div>{renderStep()}<Concept step={step} attempts={attempts} setAttempts={setAttempts}/><footer><button className="ghost" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft/> Back</button><div className="progress"><span style={{width:`${(step/10)*100}%`}}/></div><button disabled={!attempts[step]} onClick={()=>setStep(Math.min(10,step+1))}>Next step <ChevronRight/></button></footer></main><Tutor/></Shell>;
 function renderStep(){ switch(step){ case 0:return <><h2>Upload & Smart Cleaning</h2><input type="file" accept=".csv,.xlsx,.xls,.sav,.dta,.sas7bdat,.rdata" onChange={upload}/><Dashboard h={h}/><button onClick={()=>{setCleaned(cleanData(rows));setUseClean(true)}}>Auto-fix (recommended)</button><button className="ghost">Show me step-by-step and then fix</button><button className="ghost" onClick={()=>setUseClean(false)}>Ignore for now (not recommended)</button></>; case 1:return <><h2>Data Overview</h2><p>{data.length} participants × {variables.length} variables. Inferred variable types and descriptives are computed in the browser.</p><Table desc={desc}/><MiniChart data={data} numeric={numeric}/></>; case 2:return <><h2>Research Design Wizard</h2><div className="grid"><input placeholder="Main research question"/><select><option>Cross-sectional</option><option>Longitudinal</option><option>Experiment</option></select><select><option>Relationships / association</option><option>Group comparison</option><option>Prediction</option></select><input placeholder="Sample size" defaultValue={data.length}/></div><SummaryCard/></>; case 3:return <><h2>Variables & Measurement Scales</h2><div className="vargrid">{variables.map(v=><div className="pill" key={v}><b>{v}</b><select value={roles[v]||'Not used'} onChange={e=>setRoles({...roles,[v]:e.target.value})}>{['Independent variable','Dependent variable','Moderator','Mediator','Control','Confounder','Not used'].map(o=><option>{o}</option>)}</select><small>{inferType(data.map(r=>r[v]))}</small></div>)}</div></>; case 4:return <TestCards/>; case 5:return <Assumptions data={data} numeric={numeric}/>; case 6:return <><h2>In-App Statistical Analysis</h2><p>Choose variables below. The internal JavaScript statistical engine computes results directly from the cleaned dataset.</p><button onClick={runAnalysis}><FlaskConical/> Run internal analysis</button>{analysis&&<pre>{JSON.stringify(analysis,null,2)}</pre>}</>; case 7:return <><h2>Interpretation & APA-style Reporting</h2><p className="apa">{analysis?.apa||'Run an analysis first to generate APA-ready text from structured results.'}</p><button><FileText/> Copy dissertation-ready narrative</button></>; case 8:return <><h2>Visualizations</h2><MiniChart data={data} numeric={numeric}/><ScatterViz data={data}/></>; case 9:return <Tutor full/>; default:return <><h2>Summary & Export</h2><p>Export a dissertation-ready markdown report, cleaning log, and visualization images.</p><textarea readOnly value={`# StatMentor AI Results\n\nDataset: ${data.length} rows.\n\n${analysis?.apa||''}`} /><button><Download/> Download Markdown-ready report</button></>; }} }
function Shell({children,muted,setMuted}){return <div><header><b>StatMentor AI</b><button className="mute" onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Mic2/>}{muted?'Muted':'Voice on'}</button></header><div className="layout">{children}</div></div>}
function Dashboard({h}){const items=[['Duplicates',h.duplicateCount],['Missing values',Object.values(h.missing).reduce((a,b)=>a+b,0)],['Outliers / impossible',h.outliers.length],['Category inconsistencies',h.inconsistent.length]];return <div className="badges">{items.map(([k,v])=><div className={v?'warn':'ok'}>{v?<AlertTriangle/>:<CheckCircle2/>}<b>{k}</b><span>{v?v+' issue(s)':'OK'}</span><p>{v?'Recommended action available with rationale.':'No immediate action needed.'}</p></div>)}</div>}
function Table({desc}){return <div className="table">{desc.map(d=><div><b>{d.name}</b><span>{d.type}</span>{d.counts?<small>{Object.entries(d.counts).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small>:<small>N={d.N}, M={d.mean}, Mdn={d.median}, SD={d.sd}, range ${d.min}-${d.max}</small>}</div>)}</div>}
function MiniChart({data,numeric}){const v=numeric[0]; const chart=data.map((r,i)=>({name:i+1,value:Number(r[v])})).filter(d=>Number.isFinite(d.value)); return <ResponsiveContainer height={240}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#6c63ff" radius={8}/></BarChart></ResponsiveContainer>}
function ScatterViz({data}){const chart=data.map(r=>({x:Number(r.leadership),y:Number(r.performance)})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));return <ResponsiveContainer height={260}><ScatterChart><CartesianGrid/><XAxis dataKey="x" name="Leadership"/><YAxis dataKey="y" name="Performance"/><Tooltip/><Scatter data={chart} fill="#ff8a65"/></ScatterChart></ResponsiveContainer>}
function Concept({step,attempts,setAttempts}){return <section className="quiz"><h3><HelpCircle/> Concept check</h3><p>Why does StatMentor check assumptions before analysis?</p><button onClick={()=>setAttempts({...attempts,[step]:true})}>Because assumptions help choose valid tests and alternatives.</button><button onClick={()=>setAttempts({...attempts,[step]:true})}>I’m not sure yet, but I tried.</button></section>}
function TestCards(){return <><h2>Test Recommendation Engine</h2><div className="badges"><div className="ok"><CheckCircle2/><b>Multiple linear regression</b><p>Fits continuous outcomes with one or more predictors; checks linearity, homoscedasticity, and multicollinearity.</p><button>Run this with guidance</button></div><div className="warn"><AlertTriangle/><b>Spearman correlation</b><p>Alternative if normality or linearity is weak for ordinal or skewed variables.</p><button>Compare to alternative</button></div><div className="ok"><CheckCircle2/><b>Independent t-test</b><p>Use when comparing two independent groups on a continuous outcome.</p><button>Explain concept first</button></div></div></>}
function Assumptions(){return <><h2>Assumptions & Diagnostics</h2><div className="badges"><div className="ok"><CheckCircle2/><b>Linearity</b><p>Scatterplots show an approximately straight relationship.</p></div><div className="warn"><AlertTriangle/><b>Normality</b><p>Small samples may be sensitive; consider Spearman or non-parametric alternatives if severe.</p></div><div className="bad"><CircleAlert/><b>Outliers</b><p>Impossible Likert value detected in raw data; cleaned copy sets it missing.</p></div></div></>}
function Tutor({full}){return <section className={full?'card tutor full':'tutor'}><h2>AI Research Tutor</h2><p><b>SEM vs regression:</b> Regression predicts one outcome at a time. SEM can estimate linked paths among leadership, culture, engagement, and performance while modeling latent constructs.</p><p><b>Concept check:</b> If engagement transmits leadership’s effect on performance, is it a mediator or moderator?</p></section>}
function SummaryCard(){return <div className="summary"><b>Research Design Summary Card</b><p>Example: cross-sectional quantitative study examining whether leadership and culture predict engagement and performance.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
